name: Exploring Workflow Dispatch Trigger

on:
  push: 

jobs:
  job1:
    uses: ./.github/workflows/reuse.yml
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo " job1 completed"