name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
  push: 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # Check out the repository to access reusable workflow files
        uses: actions/checkout@v3
      - name: Debug: List files in workflows directory
        run: ls -R .github/workflows
      - run: echo "Exploring Workflow Dispatch Trigger"
      - uses: ./.github/workflows/reuse.yml