name: Exploring Workflow Dispatch Trigger

on:
  push: 

jobs:
  job1:
    uses: ./.github/workflows/reuse.yml
  job2:
    runs-on: ubuntu-latest
    steps:
    - run: echo " job1 completed"
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo "Name output from job1 ${{ needs.job1.outputs.firstword }}" 