name: abc
on:
    workflow_call: 
jobs:
    usage:
        name: reuse job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code  # Check out the repository to access reusable workflow files
          uses: actions/checkout@v4
        - name: kilo
          run: ls -R .github/workflows