name: abc
on:
    workflow_call: 
jobs:
    usage:
        name: reuse job
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: ls -lrth .github/workflows
        - run: echo "hello world"